feat: add the ability for users to add resources to their collections
fluid-project/hearth pull request #171
Opened 2022-08-03 18:16 UTC by chosww

Adds Livewire support to Hearth, which is used to build a Livewire component for selecting resources users want to add to their resource collections. Also, updates ResourceCollection controller and requests to have ability to include resources on resource collection create, and update. 

**Testing**

- Verify that ResourceSelect component loads all available resources
- Verify that ResourceSelect component loads any resources those are already included in a collection
- Verify adding or removing resources from ResourceSelect

2022-08-03 18:24 UTC, greatislander commented
@chosww Can you check the two failing tests and see if you can resolve them?

2022-08-03 18:29 UTC, chosww commented
> @chosww Can you check the two failing tests and see if you can resolve them?

Yep, I am working on them -- the issue seems like caused by Hearth not able to find ResourceSelect component. I will let you know once I figure it out.

2022-08-03 20:30 UTC, chosww commented
Hey @greatislander, I fixed the previous CI tests, but now I am getting code coverage failure because of the line I added in HearthCommand. Is HearthCommand something we should test or do I have to update ignore coverage check somewhere?

2022-08-24 14:02 UTC, greatislander requested changes

2022-08-29 11:59 UTC, greatislander requested changes

2022-08-29 11:59 UTC, greatislander commented on stubs/resources/views/livewire/resource-select.blade.php
> +    </div>
We can do this without needing to use Alpine at all:

```suggestion
    <div aria-live="assertive">
        @if($message)
        <p class="visually-hidden">
            {{ $message }}
        </p>
        @endif
    </div>
```

When the message is set to an empty string, Livewire will remove the visually-hidden paragraph. When the message is populated, Livewire will add it the div. Tested in VoiceOver and it works as expected!

2022-08-29 11:59 UTC, greatislander commented on stubs/resources/views/layouts/app.blade.php
> +        @vite('resources/js/app.js')
I think this change should be made in `layouts/guest.blade.php` as well.

2022-08-29 11:59 UTC, greatislander commented on stubs/app/Http/Livewire/ResourceSelect.php
> +            $this->availableResources = Resource::all()->diff($resourcesInCollection);
In the [integration test](https://github.com/fluid-project/hearth/runs/8040218647?check_suite_focus=true#step:11:74) I see this error:

```
Error: Called 'diff' on Laravel collection, but could have been retrieved as a query.
```

A quick search found this: https://laracasts.com/discuss/channels/laravel/called-diff-on-laravel-collection-but-could-have-been-retrieved-as-a-query

As I understand it, the issue here is that it's much less efficient to query ALL resources, then remove some, when one could query resources with the specified IDs instead. So I think you should make the following change:

```suggestion
            $this->availableResources = Resource::whereNotIn($resourcesInCollection->pluck('id'))->get();
```

2022-08-29 11:59 UTC, greatislander commented on stubs/app/Http/Livewire/ResourceSelect.php
> +<?php
You need to run `composer format` as there are some fixable code style issues with this file.

2022-08-30 15:29 UTC, greatislander approved these changes

2022-08-30 15:31 UTC, merged